version: v1

labels:
  - label: 'Enhancement'
    sync: true
    matcher:
      commits: '^feat.*?: .*'
      title: '^feat.*?: .*'

  - label: 'Bug'
    sync: true
    matcher:
      commits: '^fix.*?: .*'
      title: '^fix.*?: .*'

  - label: 'Documentation'
    sync: true
    matcher:
      commits: '^docs.*?: .*'
      title: '^docs.*?: .*'
      branch: '^docs/.*'
      files: ['**/*.md']

  - label: 'chore'
    sync: true
    matcher:
      commits: '^chore.*?: .*'
      title: '^chore.*?: .*'
      files: ['.github/**', '.husky/**', '.vscode/**', './.*', './*.kotlin', '**/test/**']

  - label: 'SemVer:Breaking'
    sync: true
    matcher:
      commits: '(^(.+?)!:)|(BREAKING CHANGE:)'

  - label: 'Dependencies'
    sync: true
    matcher:
      files: ['**/package.json', 'package-lock.json', '**/requirements.txt']
      author: 'renovate'
