name: Labeler
on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]
    branches: [main,develop,dev]

permissions: read-all

jobs:
  labeler:
    permissions:
      contents: read
      issues: write
      pull-requests: write
      statuses: write
      checks: write
    name: Auto-Label PRs
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4
