
on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main", "release/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

#      - name: Update CHANGELOG
#        id: changelog
#        uses: requarks/changelog-action@v1
#        with:
#          token: ${{ github.token }}
#          tag: ${{ github.ref_name }}

      - name: Build with Gradle
        run: gradle build

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: omni-craft
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          #curseforge-id: 394468
          #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Create Release
#        uses: ncipollo/release-action@v1.12.0
#        with:
#          allowUpdates: true
#          draft: false
#          makeLatest: true
#          name: ${{ github.ref_name }}
#          body: ${{ steps.changelog.outputs.changes }}
#          token: ${{ github.token }}
#
#      - name: Commit CHANGELOG.md
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          branch: main
#          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
#          file_pattern: CHANGELOG.md